### ISSUE TITLE
Downloaded the latest patch, tested it and it still doesn't work

### ISSUE THREAD

**Issue by hudsonsir** [hkadm/HostkeyResellerMod#2]
Test Platform: WHMCS 8.9.0 and 8.10.1，
The database is: Mysql5.7
I tested it and it still doesn't work, this time it's just an error, the last version imported but didn't show any products.
Error Reporting Records:
PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '?' at line 1 in /www/wwwroot/128.14.162.162/modules/addons/hostkeyresellermod/lib/HostkeyResellerModLib.php:474
Stack trace:
#0 /www/wwwroot/128.14.162.162/modules/addons/hostkeyresellermod/lib/HostkeyResellerModLib.php(474): PDO->prepare()
#1 /www/wwwroot/128.14.162.162/modules/addons/hostkeyresellermod/lib/HostkeyResellerModLib.php(484): WHMCS\Module\Addon\Hostkeyresellermod\HostkeyResellerModLib::tableExists()
#2 /www/wwwroot/128.14.162.162/modules/addons/hostkeyresellermod/lib/HostkeyResellerModLib.php(260): WHMCS\Module\Addon\Hostkeyresellermod\HostkeyResellerModLib::addProductSlug()
#3 /www/wwwroot/128.14.162.162/modules/addons/hostkeyresellermod/lib/HostkeyResellerModLib.php(160): WHMCS\Module\Addon\Hostkeyresellermod\HostkeyResellerModLib::checkProduct()
#4 /www/wwwroot/128.14.162.162/modules/addons/hostkeyresellermod/hostkeyresellermod.php(78): WHMCS\Module\Addon\Hostkeyresellermod\HostkeyResellerModLib::loadPresetsIntoDb()
#5 /www/wwwroot/128.14.162.162/admin/addonmodules.php(0): hostkeyresellermod_output()
#6 {main}
![2024-05-27 204853](https://github.com/hkadm/HostkeyResellerMod/assets/53709095/d69daad5-1f24-4128-9f5f-a183400c2315)
I provided the video, hope it helps!
https://github.com/hkadm/HostkeyResellerMod/assets/53709095/3be67bb9-5a32-47f8-aa66-3049230f429e

**Comment by hudsonsir** [comment]
I provided the video, hope it helps!
https://github.com/hkadm/HostkeyResellerMod/assets/53709095/937dd821-9d27-4fde-9589-da829e11b04f

**Comment by hkadm** [comment]
Made changes for your version of MySQL. Please try again.

**Comment by hudsonsir** [comment]
> 已针对您的 MySQL 版本进行了更改。请重试。

Thanks, I'm testing now.

**Comment by hudsonsir** [comment]
> 已针对您的 MySQL 版本进行了更改。请重试。

Thank you very much.
All products are currently imported.
One more quick question do you have to set the prices yourself?
Thanks again.

**Comment by hkadm** [comment]
Prices should be improted. To do be imported corrected please sure that you have set currency rates.

> To accurately export product prices, you need to configure currency rates relative to EUR or USD and between them. This can be done in the Payments >> Currencies section.

**Comment by hudsonsir** [comment]
> 价格应该被大幅化。要进行进口更正，请确保您已设置汇率。
> 
> > 为了准确出口产品价格，您需要配置相对于欧元或美元以及它们之间的汇率。这可以在付款>>货币部分完成。
Thank you for your reply.
Another question is that I set the default currency to USD, is this ok? Or does it have to be EUR
